core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lesson.urls')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]
urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, }), ]

lesson/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('<slug>/', views.subject_detail, name='subject_detail'),
    path('lesson/<slug>/', views.lesson_detail, name='lesson_detail'),
    path('lesson/<slug>/tasks/', views.tasks, name='tasks')
]

lesson/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Subject(models.Model):
    title = models.CharField(verbose_name=_('Title'), max_length=255)
    slug = models.SlugField(verbose_name=_('Subject slug'), max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Subject')
        verbose_name_plural = _('Subjects')


class Lesson(models.Model):
    CLASS = (
        ('NOT', _('Not defined')),
        ('FIRST_C', _('1')),
        ('SECOND_C', _('2')),
        ('THIRD_C', _('3')),
        ('FOURTH_C', _('4')),
    )

    title = models.CharField(verbose_name=_('Title'), max_length=255)
    slug = models.SlugField(verbose_name=_('Lesson slug'), max_length=255, unique=True)
    class_room = models.CharField(verbose_name=_('Class'), choices=CLASS, default=CLASS[0][1], max_length=255)
    content = RichTextUploadingField(verbose_name=_('Content'), blank=True, null=True)
    subject = models.ForeignKey(Subject, verbose_name=_('Subject'), on_delete=models.CASCADE)
    view = models.PositiveIntegerField(verbose_name=_('View'), default=0)
    date_created = models.DateTimeField(verbose_name=_('Date created'), auto_now_add=True)
    is_public = models.BooleanField(verbose_name=_('Public'), default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')
        ordering = ('date_created',)


class Task(models.Model):
    title = models.CharField(verbose_name=_('Document title'), max_length=255)
    file = models.FileField(verbose_name=_('File'), upload_to='lesson/docs/', blank=True, null=True)
    lesson = models.ForeignKey(Lesson, verbose_name=_('Lesson'), on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')

lesson/views.py
from django.shortcuts import render, get_object_or_404
from .models import Lesson, Subject, Task


def index(request):
    print(request.path)

    return render(request, 'index.html', {})


def home(request):
    lessons = Lesson.objects.filter(is_public=True)
    subjects = Subject.objects.all()

    if 'search' in request.GET:
        search = request.GET.get('search')
        lessons = Lesson.objects.filter(is_public=True, title__icontains=search)

        context = {
            'lessons': lessons,
            'subjects': subjects
        }

    if 'class-1' in request.GET:
        lessons = Lesson.objects.filter(is_public=True, class_room='FIRST_C')

        context = {
            'lessons': lessons,
            'subjects': subjects
        }
    if 'class-2' in request.GET:
        lessons = Lesson.objects.filter(is_public=True, class_room='SECOND_C')

        context = {
            'lessons': lessons,
            'subjects': subjects
        }
    if 'class-3' in request.GET:
        lessons = Lesson.objects.filter(is_public=True, class_room='THIRD_C')

        context = {
            'lessons': lessons,
            'subjects': subjects
        }
    if 'class-4' in request.GET:
        lessons = Lesson.objects.filter(is_public=True, class_room='FOURTH_C')

        context = {
            'lessons': lessons,
            'subjects': subjects
        }
    else:
        context = {
            'lessons': lessons,
            'subjects': subjects
        }
    return render(request, 'lesson/index.html', context)


# ======================================================================
def subject_detail(request, slug):
    subject = get_object_or_404(Subject, slug=slug)
    lessons = Lesson.objects.filter(subject=subject, is_public=True)
    subjects = Subject.objects.all()

    if 'search' in request.GET:
        search = request.GET.get('search')
        lessons = lessons.filter(title__icontains=search)

        context = {
            'subject': subject,
            'lessons': lessons,
            'subjects': subjects
        }

    if 'class-1' in request.GET:
        lessons = lessons.filter(class_room='FIRST_C')

        context = {
            'subject': subject,
            'lessons': lessons,
            'subjects': subjects
        }
    if 'class-2' in request.GET:
        lessons = lessons.filter(class_room='SECOND_C')

        context = {
            'subject': subject,
            'lessons': lessons,
            'subjects': subjects
        }
    if 'class-3' in request.GET:
        lessons = lessons.filter(class_room='THIRD_C')

        context = {
            'subject': subject,
            'lessons': lessons,
            'subjects': subjects
        }
    if 'class-4' in request.GET:
        lessons = lessons.filter(class_room='FOURTH_C')

        context = {
            'subject': subject,
            'lessons': lessons,
            'subjects': subjects
        }
    else:
        context = {
            'subject': subject,
            'lessons': lessons,
            'subjects': subjects
        }

    return render(request, 'lesson/subject_detail.html', context)


# ======================================================================
def lesson_detail(request, slug):
    lesson = get_object_or_404(Lesson, slug=slug)
    lessons = Lesson.objects.filter(subject=lesson.subject, class_room=lesson.class_room)
    lesson.view = lesson.view + 1
    lesson.save()
    task_list = Task.objects.filter(lesson=lesson)

    context = {
        'lesson': lesson,
        'lessons': lessons,
        'tasks': task_list
    }

    return render(request, 'lesson/lesson_detail.html', context)


# ========================================================================
def tasks(request, slug):
    lesson = get_object_or_404(Lesson, slug=slug)
    task_list = Task.objects.filter(lesson=lesson)
    lessons = Lesson.objects.filter(subject=lesson.subject, class_room=lesson.class_room)

    context = {
        'lesson': lesson,
        'lessons': lessons,
        'tasks': task_list
    }
    return render(request, 'lesson/tasks.html', context)

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Балдырған{% endblock %}</title>
    <script src="https://kit.fontawesome.com/ede4e9a973.js" crossorigin="anonymous"></script>
    <link rel="stylesheet"  href="{% static 'styles/main.css' %}">
    <link rel="shortcut icon" href="{% static '/images/icon.png' %}" type="image/x-icon">

    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
</head>
<body>
    <div id="root">
        <!-- ============================= -->
        <div class="window-sidebar">
            <ul>
                <li>
                    <a href="{% url 'home' %}"><i class="fa-solid fa-house"></i> Басты бет</a>
                </li>
                {% for subject in subjects %}
                    <li class="">
                        <p>{{ path }}</p>
                        <a href="{% url 'subject_detail' subject.slug %}"><i class="fa-solid fa-gamepad"></i> {{ subject.title }}</a>
                    </li>
                {% endfor %}
            </ul>
<!--            <form>-->
<!--                <h4>Сыныптар</h4>-->
<!--                <div class="input-group">-->
<!--                    <input type="checkbox" name="class-1" id="check1">-->
<!--                    <label for="check1">1-сынып</label>-->
<!--                </div>-->
<!--                <div class="input-group">-->
<!--                    <input type="checkbox" name="class-2" id="check2">-->
<!--                    <label for="check2">2-сынып</label>-->
<!--                </div>-->
<!--                <div class="input-group">-->
<!--                    <input type="checkbox" name="class-3" id="check3">-->
<!--                    <label for="check3">3-сынып</label>-->
<!--                </div>-->
<!--                <div class="input-group">-->
<!--                    <input type="checkbox" name="class-4" id="check4">-->
<!--                    <label for="check4">4-сынып</label>-->
<!--                </div>-->
<!--                <div class="input-group submit">-->
<!--                    <input type="submit" value="Іздеу">-->
<!--                </div>-->
<!--            </form>-->
        </div>

        <div class="wrapper">
            <div class="header">
                <div class="intro-header">
                    <a href="{% url 'home' %}" class="logo"><i class="fas fa-child"></i>baldyrgan</a>
    
                    <form class="search" method="GET">
                        <input type="text" name="search" placeholder="Поиск..." required>
                        <button><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>
    
                    <div class="menu">
                        <span><i class="fa-solid fa-bars"></i></span>
                    </div>
                </div>
            </div>
    
            <section class="main">
                <div class="sidebar" data-aos="fade-up">
                    <ul>
                        <li>
                            <a href="{% url 'home' %}"><i class="fa-solid fa-house"></i> Басты бет</a>
                        </li>
                        {% for subject in subjects %}
                            <li>
                                <a href="{% url 'subject_detail' subject.slug %}"><i class="fa-solid fa-gamepad"></i> {{ subject.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
<!--                    <form>-->
<!--                        <h4>Сыныптар</h4>-->
<!--                        <div class="input-group">-->
<!--                            <input type="checkbox" name="class-1" id="check1">-->
<!--                            <label for="check1">1-сынып</label>-->
<!--                        </div>-->
<!--                        <div class="input-group">-->
<!--                            <input type="checkbox" name="class-2" id="check2">-->
<!--                            <label for="check2">2-сынып</label>-->
<!--                        </div>-->
<!--                        <div class="input-group">-->
<!--                            <input type="checkbox" name="class-3" id="check3">-->
<!--                            <label for="check3">3-сынып</label>-->
<!--                        </div>-->
<!--                        <div class="input-group">-->
<!--                            <input type="checkbox" name="class-4" id="check4">-->
<!--                            <label for="check4">4-сынып</label>-->
<!--                        </div>-->
<!--                        <div class="input-group submit">-->
<!--                            <input type="submit" value="Іздеу">-->
<!--                        </div>-->
<!--                    </form>-->
                </div>
    
                <div class="container">
                    <div class="block" data-aos="fade-up">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </section>
        </div>
    
        <!-- =========================================================================== -->
        <div class="footer">
            <div class="intro-footer">
                <div class="logo">
                    <a href="{% url 'index' %}"><i class="fas fa-child"></i> baldyrgan</a>
                    <p>&copy; baldyrgan 2022</p>
                    <small>Барлық авторлық құқықтар сақталған</small>
                </div>
    
                <div class="ln">
                    <ul>
                        <li>
                            <a href="">Қазақша</a>
                        </li>
                        <li>
                            <a href="">Русский</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        const burgerMenu = document.querySelector('.menu');

        burgerMenu.addEventListener('click', function(e) {
            document.querySelector('.window-sidebar').classList.toggle('show');
        });
    </script>

    <script type="text/javascript">
        AOS.init();
    </script>
</body>
</html>

templates/lesson/index.html
{% extends 'layout.html' %}

{% block title %}Baldyrgan - білім беру платформасы{% endblock %}

{% block content %}
    {% for lesson in lessons %}
        <div class="box">
            <div class="poster">
                {% if lesson.subject.slug == 'scratch' %}
                    <img src="https://cdn.fs.teachablecdn.com/DYHSyOQzClnbu7UQzlhQ" alt="">
                {% else %}
                    <img src="https://www.robo.house/wp-content/uploads/2019/09/4a5c6aea25714718b0c928cfa5545c49.jpg" alt="">
                {% endif %}    
            </div>
            <h4>{{ lesson.title }}</h4>
            <div class="category">
                <span>{{ lesson.get_class_room_display }}-сынып</span>
            </div>
            <div class="body">
                <span><i class="fa-solid fa-eye"></i> {{ lesson.view }}</span>
                <span><i class="fa-solid fa-clock"></i> {{ lesson.date_created }}</span>
            </div>
            <a href="{% url 'lesson_detail' lesson.slug %}" class="link"><i class="fa-solid fa-play"></i> Бастау</a>
        </div>
    {% endfor %}
{% endblock %}

templates/lesson/lesson_detail.html
{% extends 'lesson_layout.html' %}

{% block title %}{{ lesson.title }}{% endblock %}

{% block content %}
    <div class="detail" data-aos="fade-up">
        <div class="title">
            <h3>{{ lesson.title }}</h3>
        </div>
        <div class="body">
            {{ lesson.content |safe }}
        </div>
        <div class="more">
            <p><i class="fa-solid fa-clock"></i> Шығарылған күні: {{ lesson.date_created }}ж</p>
            <p><i class="fa-solid fa-eye"></i> Қаралым саны: {{ lesson.view }}</p>
        </div>
    </div>
    <div class="tasks">
        <h3>Қосымша материалдар</h3>
        <div class="block">
            {% for task in tasks %}
            <div class="task-box">
                <span>{{ task.title }}</span>
                <a href="">{{ task.file }}</a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/lesson/subject_detail.html
{% extends 'layout.html' %}

{% block title %}{{ subject.title }}{% endblock %}

{% block content %}
    {% for lesson in lessons %}
        <div class="box">
            <div class="poster">
                {% if lesson.subject.slug == 'scratch' %}
                    <img src="https://cdn.fs.teachablecdn.com/DYHSyOQzClnbu7UQzlhQ" alt="">
                {% else %}
                    <img src="https://www.robo.house/wp-content/uploads/2019/09/4a5c6aea25714718b0c928cfa5545c49.jpg" alt="">
                {% endif %}   
            </div>
            <h4>{{ lesson.title }}</h4>
            <div class="category">
                <span>{{ lesson.get_class_room_display }}-сынып</span>
            </div>
            <div class="body">
                <span><i class="fa-solid fa-eye"></i> {{ lesson.view }} қаралым</span>
                <span><i class="fa-solid fa-clock"></i> {{ lesson.date_created }}ж</span>
            </div>
            <a href="{% url 'lesson_detail' lesson.slug %}" class="link"><i class="fa-solid fa-play"></i> Бастау</a>
        </div>
    {% endfor %}
{% endblock %}

templates/lesson_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Балдырған{% endblock %}</title>
    <link rel="shortcut icon" href="{% static '/images/icon.png' %}" type="image/x-icon">
    <script src="https://kit.fontawesome.com/ede4e9a973.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/detail.css' %}">
    
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
</head>
<body>
    <div id="root">
        <!-- ============================= -->
        <div class="window-sidebar">
            <ul>
                <li>
                    <a href="{% url 'home' %}"><i class="fa-solid fa-house"></i> Басты бет</a>
                </li>
                {% for lesson in lessons %}
                    <li>
                        <a href="{% url 'lesson_detail' lesson.slug %}"><i class="fa-solid fa-graduation-cap"></i> {{ lesson.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="wrapper">
            <div class="header">
                <div class="intro-header">
                    <a href="{% url 'home' %}" class="logo"><i class="fas fa-child"></i>baldyrgan</a>
    
                    <form class="search" method="GET">
                        <input type="text" name="search" placeholder="Поиск..." required>
                        <button><i class="fa-solid fa-magnifying-glass"></i></button>
                    </form>
    
                    <div class="menu">
                        <span><i class="fa-solid fa-bars"></i></span>
                    </div>
                </div>
            </div>
    
            <section class="main">
                <div class="sidebar" data-aos="fade-up">
                    <ul>
                        <li>
                            <a href="{% url 'home' %}"><i class="fa-solid fa-house"></i> Басты бет</a>
                        </li>
                        {% for lesson in lessons %}
                            <li>
                                <a href="{% url 'lesson_detail' lesson.slug %}"><i class="fa-solid fa-graduation-cap"></i> {{ lesson.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
    
                <div class="container">
                    <div class="block" data-aos="fade-up">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>

                <!-- ========================================================= -->
<!--                <div class="sidebar right">-->
<!--                    <ul>-->
<!--                        <li>-->
<!--                            <a href="project.html">Жобалар</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="{% url 'tasks' lesson.slug %}">Тапсырмалар</a>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
            </section>
        </div>
    
        <!-- =========================================================================== -->
        <div class="footer">
            <div class="intro-footer">
                <div class="logo">
                    <a href="{% url 'index' %}"><i class="fas fa-child"></i> baldyrgan</a>
                    <p>&copy; baldyrgan 2022</p>
                    <small>Барлық авторлық құқықтар сақталған</small>
                </div>
    
                <div class="ln">
                    <ul>
                        <li>
                            <a href="">Қазақша</a>
                        </li>
                        <li>
                            <a href="">Русский</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>
        console.log('Hello world');
        const burgerMenu = document.querySelector('.menu');

        burgerMenu.addEventListener('click', function(e) {
            document.querySelector('.window-sidebar').classList.toggle('show');
        });
    </script>

    <script type="text/javascript">
        AOS.init();
    </script>
</body>
</html>